apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinsuranceappdeployment
  labels:
    app: myinsuranceappelleta
spec:
  replicas: 8
  selector:
    matchLabels:
      app: myinsuranceappelleta
  template:
    metadata:
      labels:
        app: myinsuranceappelleta
    spec:
      imagePullSecrets:
      - name: acr-secret 
      containers:
      - name: myinsuranceappelleta-deployment-az
        image: myinsuranceapp/elletamc/myinsuranceappelleta:v8
        ports:
        - name: http
          containerPort: 5050
