apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinsuranceappdeployment
  labels:
    app: myinsuranceappelleta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myinsuranceappelleta
  template:
    metadata:
      labels:
        app: myinsuranceappelleta
    spec:
      imagePullSecrets:
      - name: acr-secret 
      containers:
      - name: myinsuranceapp-deployment-az
        image: ipanema.azurecr.io/app:latest
        ports:
        - name: http
          containerPort: 5000
