apiVersion: v1
kind: Service
metadata:
  name: myinsuranceappelleta-service
  labels:
    app: myinsuranceappelleta
spec:
  type: NodePort
  selector:
    app: myinsuranceappelleta    
  ports:
  - port: 5000
    targetPort: http
    nodePort: 32410
    protocol: TCP    
    name: http
